# .github/workflows/update_cardinals_schedule.yml

name: Update Cardinals Schedule Image

on:
  schedule:
    # Runs every day at 7:00 AM UTC (adjust as needed)
    # Use crontab guru to help: https://crontab.guru/
    - cron: '0 7 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab
  push:
    branches:
      - main # Or your default branch, e.g., master. Runs on push for testing.

jobs:
  update_image:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes to the repository (the image)
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your preferred Python version

      - name: Install OS dependencies (fonts)
        run: |
          sudo apt-get update
          # Install Liberation fonts (metrically compatible with Arial, Times New Roman, Courier New)
          sudo apt-get install -y fonts-liberation2 fontconfig
          sudo fc-cache -fv # Refresh font cache
          echo "Verifying font installation (listing liberation fonts):"
          ls -l /usr/share/fonts/truetype/liberation2 || echo "Liberation fonts not found in expected directory."

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # This assumes your requirements.txt is in the root of your repository

      - name: Run script to update image and upload to GitHub
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: python cardinals_trmnl.py # Replace with your Python script's filename if different

      - name: Verify image was created (optional check)
        run: |
          if [ -f cardinals_schedule_eink.png ]; then
            echo "Image cardinals_schedule_eink.png found."
          else
            echo "Image cardinals_schedule_eink.png NOT found after script execution."
            # exit 1 # Optionally fail the job if the image isn't created
          fi
          
      # The Python script itself handles committing and pushing the image.
